services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=healthcare-app-db'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=healthcare-user'
    ports:
      - '5432:5432'
    restart: unless-stopped
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    depends_on:
      - postgres
    restart: unless-stopped